// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2IGk4fUM_Zohz1Z1zi01mHWiP_KxIuus',
    appId: '1:225692606657:web:a2ce4b6469fa23e975f440',
    messagingSenderId: '225692606657',
    projectId: 'blacklist-moto',
    authDomain: 'blacklist-moto.firebaseapp.com',
    storageBucket: 'blacklist-moto.appspot.com',
    measurementId: 'G-0ZERH2FM89',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhrvauu0r5igblk4lqkox-HKUJJy00HTM',
    appId: '1:225692606657:android:a67e2b325901094d75f440',
    messagingSenderId: '225692606657',
    projectId: 'blacklist-moto',
    storageBucket: 'blacklist-moto.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyAH2HXvWol1P3kRwhYuvcQ4iJ0Iu-jkA',
    appId: '1:225692606657:ios:a21ddb0c5d61ee3475f440',
    messagingSenderId: '225692606657',
    projectId: 'blacklist-moto',
    storageBucket: 'blacklist-moto.appspot.com',
    iosBundleId: 'soshome-cameroun.net.blacklistMoto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyAH2HXvWol1P3kRwhYuvcQ4iJ0Iu-jkA',
    appId: '1:225692606657:ios:2a3476480f269fa875f440',
    messagingSenderId: '225692606657',
    projectId: 'blacklist-moto',
    storageBucket: 'blacklist-moto.appspot.com',
    iosBundleId: 'soshome-cameroun.net.blacklistMoto.RunnerTests',
  );
}
